apply plugin: 'application'

apply plugin: 'idea'

apply plugin: 'java'

java {
    sourceCompatibility = '22'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral() // Standardmäßig ist Maven Central Repository in Gradle enthalten
    maven { url "https://dl.bintray.com/graphstream/gs-core" }
}

dependencies {
    implementation group: 'org.graphstream', name: 'gs-core', version: '2.0'
    implementation group: 'org.graphstream', name: 'gs-algo', version: '2.0'
    implementation group: 'org.graphstream', name: 'gs-ui-javafx', version: '2.0'
    implementation group: 'org.graphstream', name: 'gs-ui-swing', version: '2.0'
    implementation 'org.openjfx:javafx-controls:20.0.1'
    implementation 'org.openjfx:javafx-fxml:20.0.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'


    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testCompileOnly 'org.junit.platform:junit-platform-commons:1.7.0'
}



processResources {
    duplicatesStrategy = 'exclude' // Warnung ausgeben, wenn doppelte Dateien gefunden werden
    // Oder:
    // duplicatesStrategy = 'warn' // Doppelte Dateien ausschließen
    // duplicatesStrategy = 'fail' // Build fehlschlagen, wenn doppelte Dateien gefunden werden
}
processTestResources {
    duplicatesStrategy = 'exclude' // Warnung ausgeben, wenn doppelte Dateien gefunden werden
    // Oder:
    // duplicatesStrategy = 'warn' // Doppelte Dateien ausschließen
    // duplicatesStrategy = 'fail' // Build fehlschlagen, wenn doppelte Dateien gefunden werden
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'

        }
    }
    test {
        resources {
            srcDir 'src/test/resources'
        }
    }
}


test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

